---
apiVersion: v1
kind: Secret
metadata:
  name: lesson-158-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:zeadailson17/gitops-lesson-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACD1Ix/D5ZL1IDZ8mv8jZSKu2YZXG8v9q5hUzqMiMRWh7AAAAJgzdUiNM3VI
    jQAAAAtzc2gtZWQyNTUxOQAAACD1Ix/D5ZL1IDZ8mv8jZSKu2YZXG8v9q5hUzqMiMRWh7A
    AAAEAE1A0oLzPcUzhlPNcoVSBRszm8ak5DVRzqzRyLPVSGkfUjH8PlkvUgNnya/yNlIq7Z
    hlcby/2rmFTOoyIxFaHsAAAAEGFyZ29jZEBnbWFpbC5jb20BAgMEBQ==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"